apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
  namespace: default
spec:
  ports:
  - port: 8010
    protocol: TCP
    targetPort: 8010
  selector:
    app: catalogue-service-app
  sessionAffinity: None
  type: ClusterIP #internal IPs withing K8s cluster,exposed to external IP with Ingress Load balancer service
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-service-app-deployment
spec:
  selector:
    matchLabels:
      app: catalogue-service-app
  replicas: 3 # tells deployment to run N pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: catalogue-service-app
    spec:
      containers:
      - name: catalogue-service-app
        image: harbor.tanzu.cloudification.in/library/catalogue-service-app-demo
        ports:
        - containerPort: 8010
          name: server
      imagePullSecrets: # Only required with private image repository like Harbor,jFrog etc
        - name: regcred